export const countries = [
    { name: "Afghanistan", code: "AF", dialCode: "93" },
    { name: "Albania", code: "AL", dialCode: "355" },
    { name: "Algeria", code: "DZ", dialCode: "213" },
    { name: "Andorra", code: "AD", dialCode: "376" },
    { name: "Angola", code: "AO", dialCode: "244" },
    { name: "Argentina", code: "AR", dialCode: "54" },
    { name: "Armenia", code: "AM", dialCode: "374" },
    { name: "Australia", code: "AU", dialCode: "61" },
    { name: "Austria", code: "AT", dialCode: "43" },
    { name: "Azerbaijan", code: "AZ", dialCode: "994" },
    { name: "Bahamas", code: "BS", dialCode: "1242" },
    { name: "Bahrain", code: "BH", dialCode: "973" },
    { name: "Bangladesh", code: "BD", dialCode: "880" },
    { name: "Barbados", code: "BB", dialCode: "1246" },
    { name: "Belarus", code: "BY", dialCode: "375" },
    { name: "Belgium", code: "BE", dialCode: "32" },
    { name: "Belize", code: "BZ", dialCode: "501" },
    { name: "Benin", code: "BJ", dialCode: "229" },
    { name: "Bhutan", code: "BT", dialCode: "975" },
    { name: "Bolivia", code: "BO", dialCode: "591" },
    { name: "Bosnia and Herzegovina", code: "BA", dialCode: "387" },
    { name: "Botswana", code: "BW", dialCode: "267" },
    { name: "Sri Lanka", code: "LK", dialCode: "94" },
    { name: "United Kingdom", code: "GB", dialCode: "44" },
    { name: "United States", code: "US", dialCode: "1" },
  ];